# Course Recommendation System
> Recommend Similiar Courses for which the user is searching/looking for

Steps involved
1. Import the data from the dataset
2. Perform Text Processing and EDA and generate insights
3. After Converting Text to numeric values, now calculate the cosine similiarity score
4. After finding the similiarity score, sort the valus which have similiar similiarity score and recommend the course
5. Integrate the Recommendation System with Flask Framework
6. Deploy the Application on Heroku Cloud Platform

### Tools & Technologies: NLP, ML, JS, Flask

## 1.

NeatText:a simple NLP package for cleaning textual data and text preprocessing. Simplifying Text Cleaning For NLP & ML

In [2]:
# importing libraries
import pandas as pd
import numpy as np
import neattext.functions as nfx
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.read_csv("udemy_course_data.csv")

In [4]:
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13

## 2.

Whenever we will have text, we will remove stopwords, special_characters

In [5]:
df['Clean_title'] = df['course_title'].apply(nfx.remove_stopwords)

df['Clean_title'] = df['Clean_title'].apply(nfx.remove_special_characters)

df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,Clean_title
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18,Ultimate Investment Banking Course
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9,Complete GST Course Certification Grow Practice
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19,Financial Modeling Business Analysts Consultants
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30,Beginner Pro Financial Analysis Excel 2017
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13,Maximize Profits Trading Options

In [6]:
df.describe()

,course_id,price,num_subscribers,num_reviews,num_lectures,profit,year,month,day
count,3.683000e+03,3683.000000,3683.000000,3683.000000,3683.000000,3.683000e+03,3683.000000,3683.000000,3683.000000
mean,6.764546e+05,65.992398,3193.371165,156.448004,40.062178,2.402885e+05,2015.433342,6.162639,15.841162
std,3.437217e+05,60.985586,9498.231406,935.078241,50.366788,1.000760e+06,1.185920,3.379314,8.780906
min,8.324000e+03,0.000000,0.000000,0.000000,0.000000,0.000000e+00,2011.000000,1.000000,1.000000
25%,4.077270e+05,20.000000,110.000000,4.000000,15.000000,1.567500e+03,2015.000000,3.000000,8.000000
50%,6.882440e+05,45.000000,911.000000,18.000000,25.000000,2.305000e+04,2016.000000,6.000000,16.000000
75%,9.617290e+05,95.000000,2537.500000,67.000000,45.000000,1.182600e+05,2016.000000,9.000000,23.000000
max,1.282064e+06,200.000000,268923.000000,27445.000000,779.000000,2.431680e+07,2017.000000,12.000000,31.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3683 non-null   int64
 1   course_title         3683 non-null   str
 2   url                  3683 non-null   str
 3   is_paid              3683 non-null   bool
 4   price                3683 non-null   int64
 5   num_subscribers      3683 non-null   int64
 6   num_reviews          3683 non-null   int64
 7   num_lectures         3683 non-null   int64
 8   level                3683 non-null   str
 9   content_duration     3683 non-null   str
 10  published_timestamp  3683 non-null   str
 11  subject              3683 non-null   str
 12  profit               3683 non-null   int64
 13  published_date       3683 non-null   str
 14  published_time       3682 non-null   str
 15  year                 3683 non-null   int64
 16  month                3683 non-null   int64
 17  day                  3683 non-null   int64
 18  Clean_title          3683 non-null   str
dtypes: bool(1), int64(9), str(9)
memory usage: 521.6 KB

### Vectorize the Clean Title

In [8]:
countvect = CountVectorizer()
cvmat = countvect.fit_transform(df['Clean_title'])
cvmat

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 18364 stored elements and shape (3683, 3564)>

In [9]:
cvmat.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(3683, 3564))

## 3.

### Cosine Similiarity

In [10]:
cos_sim = cosine_similarity(cvmat)
cos_sim

array([[1.        , 0.20412415, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.20412415, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.23570226],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.23570226, 0.        ,
        1.        ]], shape=(3683, 3683))

In [11]:
cos_sim.shape

(3683, 3683)

## 4. 
> After finding the similiarity score, sort the valus which have similiar similiarity score and recommend the course

### Recommend Course

In [12]:
df['course_title']

0                      Ultimate Investment Banking Course
1       Complete GST Course & Certification - Grow You...
2       Financial Modeling for Business Analysts and C...
3       Beginner to Pro - Financial Analysis in Excel ...
4            How To Maximize Your Profits Trading Options
                              ...
3678    Learn jQuery from Scratch - Master of JavaScri...
3679    How To Design A WordPress Website With No Codi...
3680                        Learn and Build using Polymer
3681    CSS Animations: Create Amazing Effects on Your...
3682    Using MODX CMS to Build Websites: A Beginner's...
Name: course_title, Length: 3683, dtype: str

In [13]:
title = 'How To Maximize Your Profits Trading Options'

In [14]:
course_index = pd.Series(df.index, index=df['course_title']).drop_duplicates()

course_index[title]

np.int64(4)

In [15]:
index = course_index['How To Maximize Your Profits Trading Options']
index

np.int64(4)

In [16]:
scores = list(enumerate(cos_sim[index]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(1.0)),
 (5, np.float64(0.20412414523193154)),
 (6, np.float64(0.20412414523193154)),
 (7, np.float64(0.1889822365046136)),
 (8, np.float64(0.3779644730092272)),
 (9, np.float64(0.0)),
 (10, np.float64(0.20412414523193154)),
 (11, np.float64(0.5)),
 (12, np.float64(0.0)),
 (13, np.float64(0.17677669529663687)),
 (14, np.float64(0.35355339059327373)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.1889822365046136)),
 (18, np.float64(0.22360679774997896)),
 (19, np.float64(0.0)),
 (20, np.float64(0.30151134457776363)),
 (21, np.float64(0.20412414523193154)),
 (22, np.float64(0.1889822365046136)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.1889822365046136)),
 (30, np.float64(0.35355339059327373)),
 (31, np.float64(0.0)),
 (32, np.float64(0.0)),
 (33, np.float64(0.3779644730092272)),
 (34, np.float64(0.0)),
 (35, np.float64(0.3779644730092272)),
 (36, np.float64(0.30151134457776363)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.0)),
 (42, np.float64(0.0)),
 (43, np.float64(0.5669467095138407)),
 (44, np.float64(0.35355339059327373)),
 (45, np.float64(0.0)),
 (46, np.float64(0.35355339059327373)),
 (47, np.float64(0.0)),
 (48, np.float64(0.35355339059327373)),
 (49, np.float64(0.4082482904638631)),
 (50, np.float64(0.22360679774997896)),
 (51, np.float64(0.0)),
 (52, np.float64(0.1889822365046136)),
 (53, np.float64(0.0)),
 (54, np.float64(0.4082482904638631)),
 (55, np.float64(0.0)),
 (56, np.float64(0.0)),
 (57, np.float64(0.20412414523193154)),
 (58, np.float64(0.0)),
 (59, np.float64(0.5)),
 (60, np.float64(0.0)),
 (61, np.float64(0.20412414523193154)),
 (62, np.float64(0.3333333333333333)),
 (63, np.float64(0.0)),
 (64, np.float64(0.17677669529663687)),
 (65, np.float64(0.0)),
 (66, np.float64(0.4472135954999579)),
 (67, np.float64(0.25)),
 (68, np.float64(0.5)),
 (69, np.float64(0.0)),
 (70, np.float64(0.17677669529663687)),
 (71, np.float64(0.5)),
 (72, np.float64(0.4082482904638631)),
 (73, np.float64(0.16666666666666666)),
 (74, np.float64(0.0)),
 (75, np.float64(0.35355339059327373)),
 (76, np.float64(0.0)),
 (77, np.float64(0.25)),
 (78, np.float64(0.25)),
 (79, np.float64(0.22360679774997896)),
 (80, np.float64(0.0)),
 (81, np.float64(0.17677669529663687)),
 (82, np.float64(0.0)),
 (83, np.float64(0.0)),
 (84, np.float64(0.25)),
 (85, np.float64(0.4082482904638631)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0)),
 (88, np.float64(0.25)),
 (89, np.float64(0.35355339059327373)),
 (90, np.float64(0.22360679774997896)),
 (91, np.float64(0.0)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.5303300858899106)),
 (97, np.float64(0.5)),
 (98, np.float64(0.0)),
 (99, np.float64(0.2886751345948129)),
 (100, np.float64(0.0)),
 (101, np.float64(0.0)),
 (102, np.float64(0.3779644730092272)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.4082482904638631)),
 (108, np.float64(0.2886751345948129)),
 (109, np.float64(0.3779644730092272)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.17677669529663687)),
 (113, np.float64(0.3779644730092272)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.1889822365046136)),
 (118, np.float64(0.2886751345948129)),
 (119, np.float64(0.17677669529663687)),
 (120, np.float64(0.15811388300841897)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (125, np.float64(0.1889822365046136)),
 (126, np.float64(0.0)),
 (127, np.float64(0.0)),
 (128, np.float64(0.0)),
 (129, np.float64(0.15075567228888181)),
 (130, np.float64(0.0)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (135, np.float64(0.25)),
 (136, np.float64(0.0)),
 (137, np.float64(0.17677669529663687)),
 (138, np.float64(0.5303300858899106)),
 (139, np.float64(0.0)),
 (140, np.float64(0.0)),
 (141, np.float64(0.22360679774997896)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (144, np.float64(0.25)),
 (145, np.float64(0.0)),
 (146, np.float64(0.0)),
 (147, np.float64(0.20412414523193154)),
 (148, np.float64(0.0)),
 (149, np.float64(0.35355339059327373)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (152, np.float64(0.17677669529663687)),
 (153, np.float64(0.35355339059327373)),
 (154, np.float64(0.20412414523193154)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.3779644730092272)),
 (158, np.float64(0.0)),
 (159, np.float64(0.0)),
 (160, np.float64(0.4082482904638631)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.25)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.4082482904638631)),
 (168, np.float64(0.0)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.15811388300841897)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (176, np.float64(0.16666666666666666)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.0)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.17677669529663687)),
 (185, np.float64(0.0)),
 (186, np.float64(0.3779644730092272)),
 (187, np.float64(0.22360679774997896)),
 (188, np.float64(0.22360679774997896)),
 (189, np.float64(0.0)),
 (190, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.0)),
 (194, np.float64(0.0)),
 (195, np.float64(0.5303300858899106)),
 (196, np.float64(0.22360679774997896)),
 (197, np.float64(0.0)),
 (198, np.float64(0.20412414523193154)),
 (199, np.float64(0.0)),
 (200, np.float64(0.35355339059327373)),
 (201, np.float64(0.30151134457776363)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.4082482904638631)),
 (206, np.float64(0.0)),
 (207, np.float64(0.20412414523193154)),
 (208, np.float64(0.25)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.20412414523193154)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.20412414523193154)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.20412414523193154)),
 (221, np.float64(0.22360679774997896)),
 (222, np.float64(0.4472135954999579)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (225, np.float64(0.1889822365046136)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0)),
 (230, np.float64(0.0)),
 (231, np.float64(0.0)),
 (232, np.float64(0.1889822365046136)),
 (233, np.float64(0.22360679774997896)),
 (234, np.float64(0.4472135954999579)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.20412414523193154)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.20412414523193154)),
 (247, np.float64(0.0)),
 (248, np.float64(0.22360679774997896)),
 (249, np.float64(0.0)),
 (250, np.float64(0.15811388300841897)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (256, np.float64(0.2773500981126146)),
 (257, np.float64(0.0)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.17677669529663687)),
 (267, np.float64(0.0)),
 (268, np.float64(0.1889822365046136)),
 (269, np.float64(0.0)),
 (270, np.float64(0.0)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0)),
 (278, np.float64(0.22360679774997896)),
 (279, np.float64(0.0)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.17677669529663687)),
 (284, np.float64(0.25)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.4082482904638631)),
 (296, np.float64(0.20412414523193154)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.25)),
 (300, np.float64(0.20412414523193154)),
 (301, np.float64(0.0)),
 (302, np.float64(0.2886751345948129)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0)),
 (305, np.float64(0.0)),
 (306, np.float64(0.20412414523193154)),
 (307, np.float64(0.0)),
 (308, np.float64(0.1889822365046136)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0)),
 (311, np.float64(0.0)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.0)),
 (315, np.float64(0.3333333333333333)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.25)),
 (321, np.float64(0.0)),
 (322, np.float64(0.22360679774997896)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.22360679774997896)),
 (330, np.float64(0.5)),
 (331, np.float64(0.20412414523193154)),
 (332, np.float64(0.0)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.0)),
 (345, np.float64(0.0)),
 (346, np.float64(0.35355339059327373)),
 (347, np.float64(0.1889822365046136)),
 (348, np.float64(0.0)),
 (349, np.float64(0.17677669529663687)),
 (350, np.float64(0.25)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0)),
 (353, np.float64(0.4082482904638631)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.25)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.35355339059327373)),
 (362, np.float64(0.17677669529663687)),
 (363, np.float64(0.3779644730092272)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.35355339059327373)),
 (367, np.float64(0.1889822365046136)),
 (368, np.float64(0.0)),
 (369, np.float64(0.4472135954999579)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.17677669529663687)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.35355339059327373)),
 (378, np.float64(0.5)),
 (379, np.float64(0.20412414523193154)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.0)),
 (386, np.float64(0.0)),
 (387, np.float64(0.2886751345948129)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0)),
 (390, np.float64(0.0)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.25)),
 (395, np.float64(0.0)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.30151134457776363)),
 (399, np.float64(0.4330127018922194)),
 (400, np.float64(0.0)),
 (401, np.float64(0.22360679774997896)),
 (402, np.float64(0.4082482904638631)),
 (403, np.float64(0.2886751345948129)),
 (404, np.float64(0.0)),
 (405, np.float64(0.16666666666666666)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.25)),
 (409, np.float64(0.0)),
 (410, np.float64(0.5773502691896258)),
 (411, np.float64(0.4082482904638631)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.35355339059327373)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.0)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.0)),
 (426, np.float64(0.0)),
 (427, np.float64(0.0)),
 (428, np.float64(0.0)),
 (429, np.float64(0.25)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.0)),
 (434, np.float64(0.3779644730092272)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.4472135954999579)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (444, np.float64(0.5303300858899106)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.25)),
 (449, np.float64(0.0)),
 (450, np.float64(0.1889822365046136)),
 (451, np.float64(0.35355339059327373)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.0)),
 (455, np.float64(0.0)),
 (456, np.float64(0.22360679774997896)),
 (457, np.float64(0.1889822365046136)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.4472135954999579)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.2886751345948129)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.35355339059327373)),
 (472, np.float64(0.0)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.0)),
 (477, np.float64(0.2886751345948129)),
 (478, np.float64(0.0)),
 (479, np.float64(0.2886751345948129)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.1889822365046136)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.0)),
 (489, np.float64(0.0)),
 (490, np.float64(0.20412414523193154)),
 (491, np.float64(0.0)),
 (492, np.float64(0.0)),
 (493, np.float64(0.25)),
 (494, np.float64(0.0)),
 (495, np.float64(0.20412414523193154)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.20412414523193154)),
 (499, np.float64(0.0)),
 (500, np.float64(0.25)),
 (501, np.float64(0.22360679774997896)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.20412414523193154)),
 (505, np.float64(0.0)),
 (506, np.float64(0.0)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.20412414523193154)),
 (510, np.float64(0.3779644730092272)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.1889822365046136)),
 (514, np.float64(0.5)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.0)),
 (524, np.float64(0.0)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.1889822365046136)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.0)),
 (533, np.float64(0.25)),
 (534, np.float64(0.20412414523193154)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.0)),
 (538, np.float64(0.2886751345948129)),
 (539, np.float64(0.0)),
 (540, np.float64(0.0)),
 (541, np.float64(0.1889822365046136)),
 (542, np.float64(0.20412414523193154)),
 (543, np.float64(0.0)),
 (544, np.float64(0.0)),
 (545, np.float64(0.0)),
 (546, np.float64(0.0)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.0)),
 (551, np.float64(0.22360679774997896)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.20412414523193154)),
 (556, np.float64(0.0)),
 (557, np.float64(0.0)),
 (558, np.float64(0.1889822365046136)),
 (559, np.float64(0.25)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.20412414523193154)),
 (563, np.float64(0.0)),
 (564, np.float64(0.1889822365046136)),
 (565, np.float64(0.0)),
 (566, np.float64(0.35355339059327373)),
 (567, np.float64(0.0)),
 (568, np.float64(0.0)),
 (569, np.float64(0.0)),
 (570, np.float64(0.25)),
 (571, np.float64(0.0)),
 (572, np.float64(0.0)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.0)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.0)),
 (580, np.float64(0.20412414523193154)),
 (581, np.float64(0.0)),
 (582, np.float64(0.0)),
 (583, np.float64(0.2886751345948129)),
 (584, np.float64(0.0)),
 (585, np.float64(0.20412414523193154)),
 (586, np.float64(0.0)),
 (587, np.float64(0.0)),
 (588, np.float64(0.1889822365046136)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.0)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.0)),
 (596, np.float64(0.0)),
 (597, np.float64(0.0)),
 (598, np.float64(0.25)),
 (599, np.float64(0.0)),
 (600, np.float64(0.17677669529663687)),
 (601, np.float64(0.16666666666666666)),
 (602, np.float64(0.0)),
 (603, np.float64(0.0)),
 (604, np.float64(0.22360679774997896)),
 (605, np.float64(0.0)),
 (606, np.float64(0.0)),
 (607, np.float64(0.20412414523193154)),
 (608, np.float64(0.0)),
 (609, np.float64(0.0)),
 (610, np.float64(0.0)),
 (611, np.float64(0.0)),
 (612, np.float64(0.0)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.3333333333333333)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),
 (621, np.float64(0.0)),
 (622, np.float64(0.0)),
 (623, np.float64(0.0)),
 (624, np.float64(0.0)),
 (625, np.float64(0.0)),
 (626, np.float64(0.22360679774997896)),
 (627, np.float64(0.0)),
 (628, np.float64(0.35355339059327373)),
 (629, np.float64(0.0)),
 (630, np.float64(0.0)),
 (631, np.float64(0.0)),
 (632, np.float64(0.22360679774997896)),
 (633, np.float64(0.0)),
 (634, np.float64(0.0)),
 (635, np.float64(0.0)),
 (636, np.float64(0.0)),
 (637, np.float64(0.22360679774997896)),
 (638, np.float64(0.0)),
 (639, np.float64(0.0)),
 (640, np.float64(0.0)),
 (641, np.float64(0.22360679774997896)),
 (642, np.float64(0.0)),
 (643, np.float64(0.0)),
 (644, np.float64(0.0)),
 (645, np.float64(0.0)),
 (646, np.float64(0.0)),
 (647, np.float64(0.5)),
 (648, np.float64(0.2886751345948129)),
 (649, np.float64(0.0)),
 (650, np.float64(0.3779644730092272)),
 (651, np.float64(0.0)),
 (652, np.float64(0.2886751345948129)),
 (653, np.float64(0.0)),
 (654, np.float64(0.20412414523193154)),
 (655, np.float64(0.20412414523193154)),
 (656, np.float64(0.0)),
 (657, np.float64(0.0)),
 (658, np.float64(0.22360679774997896)),
 (659, np.float64(0.0)),
 (660, np.float64(0.0)),
 (661, np.float64(0.0)),
 (662, np.float64(0.0)),
 (663, np.float64(0.0)),
 (664, np.float64(0.0)),
 (665, np.float64(0.0)),
 (666, np.float64(0.22360679774997896)),
 (667, np.float64(0.0)),
 (668, np.float64(0.0)),
 (669, np.float64(0.0)),
 (670, np.float64(0.0)),
 (671, np.float64(0.0)),
 (672, np.float64(0.0)),
 (673, np.float64(0.0)),
 (674, np.float64(0.0)),
 (675, np.float64(0.0)),
 (676, np.float64(0.0)),
 (677, np.float64(0.1889822365046136)),
 (678, np.float64(0.0)),
 (679, np.float64(0.0)),
 (680, np.float64(0.0)),
 (681, np.float64(0.0)),
 (682, np.float64(0.0)),
 (683, np.float64(0.31622776601683794)),
 (684, np.float64(0.0)),
 (685, np.float64(0.0)),
 (686, np.float64(0.0)),
 (687, np.float64(0.0)),
 (688, np.float64(0.0)),

In [17]:
sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
sorted_scores

[(4, np.float64(1.0)),
 (410, np.float64(0.5773502691896258)),
 (43, np.float64(0.5669467095138407)),
 (96, np.float64(0.5303300858899106)),
 (138, np.float64(0.5303300858899106)),
 (195, np.float64(0.5303300858899106)),
 (444, np.float64(0.5303300858899106)),
 (803, np.float64(0.5303300858899106)),
 (11, np.float64(0.5)),
 (59, np.float64(0.5)),
 (68, np.float64(0.5)),
 (71, np.float64(0.5)),
 (97, np.float64(0.5)),
 (330, np.float64(0.5)),
 (378, np.float64(0.5)),
 (514, np.float64(0.5)),
 (647, np.float64(0.5)),
 (738, np.float64(0.5)),
 (947, np.float64(0.5)),
 (991, np.float64(0.5)),
 (811, np.float64(0.45226701686664544)),
 (66, np.float64(0.4472135954999579)),
 (222, np.float64(0.4472135954999579)),
 (234, np.float64(0.4472135954999579)),
 (369, np.float64(0.4472135954999579)),
 (439, np.float64(0.4472135954999579)),
 (463, np.float64(0.4472135954999579)),
 (766, np.float64(0.4472135954999579)),
 (829, np.float64(0.4472135954999579)),
 (399, np.float64(0.4330127018922194)),
 (49, np.float64(0.4082482904638631)),
 (54, np.float64(0.4082482904638631)),
 (72, np.float64(0.4082482904638631)),
 (85, np.float64(0.4082482904638631)),
 (107, np.float64(0.4082482904638631)),
 (160, np.float64(0.4082482904638631)),
 (167, np.float64(0.4082482904638631)),
 (205, np.float64(0.4082482904638631)),
 (295, np.float64(0.4082482904638631)),
 (353, np.float64(0.4082482904638631)),
 (402, np.float64(0.4082482904638631)),
 (411, np.float64(0.4082482904638631)),
 (802, np.float64(0.4082482904638631)),
 (953, np.float64(0.4082482904638631)),
 (956, np.float64(0.4082482904638631)),
 (1002, np.float64(0.4082482904638631)),
 (8, np.float64(0.3779644730092272)),
 (33, np.float64(0.3779644730092272)),
 (35, np.float64(0.3779644730092272)),
 (102, np.float64(0.3779644730092272)),
 (109, np.float64(0.3779644730092272)),
 (113, np.float64(0.3779644730092272)),
 (157, np.float64(0.3779644730092272)),
 (186, np.float64(0.3779644730092272)),
 (363, np.float64(0.3779644730092272)),
 (434, np.float64(0.3779644730092272)),
 (510, np.float64(0.3779644730092272)),
 (650, np.float64(0.3779644730092272)),
 (798, np.float64(0.3779644730092272)),
 (900, np.float64(0.3779644730092272)),
 (14, np.float64(0.35355339059327373)),
 (30, np.float64(0.35355339059327373)),
 (44, np.float64(0.35355339059327373)),
 (46, np.float64(0.35355339059327373)),
 (48, np.float64(0.35355339059327373)),
 (75, np.float64(0.35355339059327373)),
 (89, np.float64(0.35355339059327373)),
 (149, np.float64(0.35355339059327373)),
 (153, np.float64(0.35355339059327373)),
 (200, np.float64(0.35355339059327373)),
 (346, np.float64(0.35355339059327373)),
 (361, np.float64(0.35355339059327373)),
 (366, np.float64(0.35355339059327373)),
 (377, np.float64(0.35355339059327373)),
 (416, np.float64(0.35355339059327373)),
 (451, np.float64(0.35355339059327373)),
 (471, np.float64(0.35355339059327373)),
 (566, np.float64(0.35355339059327373)),
 (628, np.float64(0.35355339059327373)),
 (708, np.float64(0.35355339059327373)),
 (794, np.float64(0.35355339059327373)),
 (864, np.float64(0.35355339059327373)),
 (909, np.float64(0.35355339059327373)),
 (954, np.float64(0.35355339059327373)),
 (963, np.float64(0.35355339059327373)),
 (1023, np.float64(0.35355339059327373)),
 (1112, np.float64(0.35355339059327373)),
 (1115, np.float64(0.35355339059327373)),
 (1134, np.float64(0.35355339059327373)),
 (1136, np.float64(0.35355339059327373)),
 (1141, np.float64(0.35355339059327373)),
 (1151, np.float64(0.35355339059327373)),
 (62, np.float64(0.3333333333333333)),
 (315, np.float64(0.3333333333333333)),
 (618, np.float64(0.3333333333333333)),
 (683, np.float64(0.31622776601683794)),
 (20, np.float64(0.30151134457776363)),
 (36, np.float64(0.30151134457776363)),
 (201, np.float64(0.30151134457776363)),
 (398, np.float64(0.30151134457776363)),
 (709, np.float64(0.30151134457776363)),
 (99, np.float64(0.2886751345948129)),
 (108, np.float64(0.2886751345948129)),
 (118, np.float64(0.2886751345948129)),
 (302, np.float64(0.2886751345948129)),
 (387, np.float64(0.2886751345948129)),
 (403, np.float64(0.2886751345948129)),
 (468, np.float64(0.2886751345948129)),
 (477, np.float64(0.2886751345948129)),
 (479, np.float64(0.2886751345948129)),
 (538, np.float64(0.2886751345948129)),
 (583, np.float64(0.2886751345948129)),
 (648, np.float64(0.2886751345948129)),
 (652, np.float64(0.2886751345948129)),
 (745, np.float64(0.2886751345948129)),
 (777, np.float64(0.2886751345948129)),
 (823, np.float64(0.2886751345948129)),
 (833, np.float64(0.2886751345948129)),
 (844, np.float64(0.2886751345948129)),
 (863, np.float64(0.2886751345948129)),
 (883, np.float64(0.2886751345948129)),
 (948, np.float64(0.2886751345948129)),
 (962, np.float64(0.2886751345948129)),
 (1005, np.float64(0.2886751345948129)),
 (1089, np.float64(0.2886751345948129)),
 (1171, np.float64(0.2886751345948129)),
 (256, np.float64(0.2773500981126146)),
 (67, np.float64(0.25)),
 (77, np.float64(0.25)),
 (78, np.float64(0.25)),
 (84, np.float64(0.25)),
 (88, np.float64(0.25)),
 (135, np.float64(0.25)),
 (144, np.float64(0.25)),
 (164, np.float64(0.25)),
 (208, np.float64(0.25)),
 (284, np.float64(0.25)),
 (299, np.float64(0.25)),
 (320, np.float64(0.25)),
 (350, np.float64(0.25)),
 (356, np.float64(0.25)),
 (394, np.float64(0.25)),
 (408, np.float64(0.25)),
 (429, np.float64(0.25)),
 (448, np.float64(0.25)),
 (493, np.float64(0.25)),
 (500, np.float64(0.25)),
 (533, np.float64(0.25)),
 (559, np.float64(0.25)),
 (570, np.float64(0.25)),
 (598, np.float64(0.25)),
 (694, np.float64(0.25)),
 (696, np.float64(0.25)),
 (764, np.float64(0.25)),
 (769, np.float64(0.25)),
 (815, np.float64(0.25)),
 (921, np.float64(0.25)),
 (1012, np.float64(0.25)),
 (1021, np.float64(0.25)),
 (1135, np.float64(0.25)),
 (18, np.float64(0.22360679774997896)),
 (50, np.float64(0.22360679774997896)),
 (79, np.float64(0.22360679774997896)),
 (90, np.float64(0.22360679774997896)),
 (141, np.float64(0.22360679774997896)),
 (187, np.float64(0.22360679774997896)),
 (188, np.float64(0.22360679774997896)),
 (196, np.float64(0.22360679774997896)),
 (221, np.float64(0.22360679774997896)),
 (233, np.float64(0.22360679774997896)),
 (248, np.float64(0.22360679774997896)),
 (278, np.float64(0.22360679774997896)),
 (322, np.float64(0.22360679774997896)),
 (329, np.float64(0.22360679774997896)),
 (401, np.float64(0.22360679774997896)),
 (456, np.float64(0.22360679774997896)),
 (501, np.float64(0.22360679774997896)),
 (551, np.float64(0.22360679774997896)),
 (604, np.float64(0.22360679774997896)),
 (626, np.float64(0.22360679774997896)),
 (632, np.float64(0.22360679774997896)),
 (637, np.float64(0.22360679774997896)),
 (641, np.float64(0.22360679774997896)),
 (658, np.float64(0.22360679774997896)),
 (666, np.float64(0.22360679774997896)),
 (691, np.float64(0.22360679774997896)),
 (697, np.float64(0.22360679774997896)),
 (704, np.float64(0.22360679774997896)),
 (706, np.float64(0.22360679774997896)),
 (715, np.float64(0.22360679774997896)),
 (756, np.float64(0.22360679774997896)),
 (760, np.float64(0.22360679774997896)),
 (774, np.float64(0.22360679774997896)),
 (790, np.float64(0.22360679774997896)),
 (834, np.float64(0.22360679774997896)),
 (857, np.float64(0.22360679774997896)),
 (867, np.float64(0.22360679774997896)),
 (940, np.float64(0.22360679774997896)),
 (965, np.float64(0.22360679774997896)),
 (1043, np.float64(0.22360679774997896)),
 (1054, np.float64(0.22360679774997896)),
 (1091, np.float64(0.22360679774997896)),
 (1100, np.float64(0.22360679774997896)),
 (1122, np.float64(0.22360679774997896)),
 (1124, np.float64(0.22360679774997896)),
 (1166, np.float64(0.22360679774997896)),
 (1181, np.float64(0.22360679774997896)),
 (5, np.float64(0.20412414523193154)),
 (6, np.float64(0.20412414523193154)),
 (10, np.float64(0.20412414523193154)),
 (21, np.float64(0.20412414523193154)),
 (57, np.float64(0.20412414523193154)),
 (61, np.float64(0.20412414523193154)),
 (147, np.float64(0.20412414523193154)),
 (154, np.float64(0.20412414523193154)),
 (198, np.float64(0.20412414523193154)),
 (207, np.float64(0.20412414523193154)),
 (212, np.float64(0.20412414523193154)),
 (217, np.float64(0.20412414523193154)),
 (220, np.float64(0.20412414523193154)),
 (240, np.float64(0.20412414523193154)),
 (246, np.float64(0.20412414523193154)),
 (296, np.float64(0.20412414523193154)),
 (300, np.float64(0.20412414523193154)),
 (306, np.float64(0.20412414523193154)),
 (331, np.float64(0.20412414523193154)),
 (379, np.float64(0.20412414523193154)),
 (490, np.float64(0.20412414523193154)),
 (495, np.float64(0.20412414523193154)),
 (498, np.float64(0.20412414523193154)),
 (504, np.float64(0.20412414523193154)),
 (509, np.float64(0.20412414523193154)),
 (534, np.float64(0.20412414523193154)),
 (542, np.float64(0.20412414523193154)),
 (555, np.float64(0.20412414523193154)),
 (562, np.float64(0.20412414523193154)),
 (580, np.float64(0.20412414523193154)),
 (585, np.float64(0.20412414523193154)),
 (607, np.float64(0.20412414523193154)),
 (654, np.float64(0.20412414523193154)),
 (655, np.float64(0.20412414523193154)),
 (699, np.float64(0.20412414523193154)),
 (702, np.float64(0.20412414523193154)),
 (734, np.float64(0.20412414523193154)),
 (776, np.float64(0.20412414523193154)),
 (797, np.float64(0.20412414523193154)),
 (809, np.float64(0.20412414523193154)),
 (880, np.float64(0.20412414523193154)),
 (958, np.float64(0.20412414523193154)),
 (972, np.float64(0.20412414523193154)),
 (1093, np.float64(0.20412414523193154)),
 (1123, np.float64(0.20412414523193154)),
 (1127, np.float64(0.20412414523193154)),
 (1140, np.float64(0.20412414523193154)),
 (1161, np.float64(0.20412414523193154)),
 (7, np.float64(0.1889822365046136)),
 (17, np.float64(0.1889822365046136)),
 (22, np.float64(0.1889822365046136)),
 (29, np.float64(0.1889822365046136)),
 (52, np.float64(0.1889822365046136)),
 (117, np.float64(0.1889822365046136)),
 (125, np.float64(0.1889822365046136)),
 (225, np.float64(0.1889822365046136)),
 (232, np.float64(0.1889822365046136)),
 (268, np.float64(0.1889822365046136)),
 (308, np.float64(0.1889822365046136)),
 (347, np.float64(0.1889822365046136)),
 (367, np.float64(0.1889822365046136)),
 (450, np.float64(0.1889822365046136)),
 (457, np.float64(0.1889822365046136)),
 (482, np.float64(0.1889822365046136)),
 (513, np.float64(0.1889822365046136)),
 (529, np.float64(0.1889822365046136)),
 (541, np.float64(0.1889822365046136)),
 (558, np.float64(0.1889822365046136)),
 (564, np.float64(0.1889822365046136)),
 (588, np.float64(0.1889822365046136)),
 (677, np.float64(0.1889822365046136)),
 (758, np.float64(0.1889822365046136)),
 (793, np.float64(0.1889822365046136)),
 (856, np.float64(0.1889822365046136)),
 (874, np.float64(0.1889822365046136)),
 (899, np.float64(0.1889822365046136)),
 (904, np.float64(0.1889822365046136)),
 (957, np.float64(0.1889822365046136)),
 (960, np.float64(0.1889822365046136)),
 (964, np.float64(0.1889822365046136)),
 (1008, np.float64(0.1889822365046136)),
 (1032, np.float64(0.1889822365046136)),
 (1132, np.float64(0.1889822365046136)),
 (1133, np.float64(0.1889822365046136)),
 (1165, np.float64(0.1889822365046136)),
 (1177, np.float64(0.1889822365046136)),
 (3162, np.float64(0.1889822365046136)),
 (13, np.float64(0.17677669529663687)),
 (64, np.float64(0.17677669529663687)),
 (70, np.float64(0.17677669529663687)),
 (81, np.float64(0.17677669529663687)),
 (112, np.float64(0.17677669529663687)),
 (119, np.float64(0.17677669529663687)),
 (137, np.float64(0.17677669529663687)),
 (152, np.float64(0.17677669529663687)),
 (184, np.float64(0.17677669529663687)),
 (266, np.float64(0.17677669529663687)),
 (283, np.float64(0.17677669529663687)),
 (349, np.float64(0.17677669529663687)),
 (362, np.float64(0.17677669529663687)),
 (372, np.float64(0.17677669529663687)),
 (600, np.float64(0.17677669529663687)),
 (735, np.float64(0.17677669529663687)),
 (742, np.float64(0.17677669529663687)),
 (845, np.float64(0.17677669529663687)),
 (1051, np.float64(0.17677669529663687)),
 (1065, np.float64(0.17677669529663687)),
 (73, np.float64(0.16666666666666666)),
 (176, np.float64(0.16666666666666666)),
 (405, np.float64(0.16666666666666666)),
 (601, np.float64(0.16666666666666666)),
 (997, np.float64(0.16666666666666666)),
 (1131, np.float64(0.16666666666666666)),
 (120, np.float64(0.15811388300841897)),
 (171, np.float64(0.15811388300841897)),
 (250, np.float64(0.15811388300841897)),
 (1074, np.float64(0.15811388300841897)),
 (129, np.float64(0.15075567228888181)),
 (1031, np.float64(0.14433756729740646)),
 (1156, np.float64(0.14433756729740646)),
 (0, np.float64(0.0)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (9, np.float64(0.0)),
 (12, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (19, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (31, np.float64(0.0)),
 (32, np.float64(0.0)),
 (34, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.0)),
 (42, np.float64(0.0)),
 (45, np.float64(0.0)),
 (47, np.float64(0.0)),
 (51, np.float64(0.0)),
 (53, np.float64(0.0)),
 (55, np.float64(0.0)),
 (56, np.float64(0.0)),
 (58, np.float64(0.0)),
 (60, np.float64(0.0)),
 (63, np.float64(0.0)),
 (65, np.float64(0.0)),
 (69, np.float64(0.0)),
 (74, np.float64(0.0)),
 (76, np.float64(0.0)),
 (80, np.float64(0.0)),
 (82, np.float64(0.0)),
 (83, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0)),
 (91, np.float64(0.0)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (98, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (126, np.float64(0.0)),
 (127, np.float64(0.0)),
 (128, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (136, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.0)),
 (148, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (158, np.float64(0.0)),
 (159, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (168, np.float64(0.0)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.0)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (185, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.0)),
 (194, np.float64(0.0)),
 (197, np.float64(0.0)),
 (199, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (206, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0)),
 (230, np.float64(0.0)),
 (231, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (247, np.float64(0.0)),
 (249, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (257, np.float64(0.0)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (267, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.0)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0)),
 (279, np.float64(0.0)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (301, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0)),
 (305, np.float64(0.0)),
 (307, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0)),
 (311, np.float64(0.0)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (321, np.float64(0.0)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (332, np.float64(0.0)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.0)),
 (345, np.float64(0.0)),
 (348, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (368, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.0)),
 (386, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0)),
 (390, np.float64(0.0)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (395, np.float64(0.0)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (400, np.float64(0.0)),
 (404, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (409, np.float64(0.0)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.0)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.0)),
 (426, np.float64(0.0)),
 (427, np.float64(0.0)),
 (428, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (449, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.0)),
 (455, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),

In [18]:
selected_course_index = [i[0] for i in sorted_scores[1:]]
selected_course_index

[410,
 43,
 96,
 138,
 195,
 444,
 803,
 11,
 59,
 68,
 71,
 97,
 330,
 378,
 514,
 647,
 738,
 947,
 991,
 811,
 66,
 222,
 234,
 369,
 439,
 463,
 766,
 829,
 399,
 49,
 54,
 72,
 85,
 107,
 160,
 167,
 205,
 295,
 353,
 402,
 411,
 802,
 953,
 956,
 1002,
 8,
 33,
 35,
 102,
 109,
 113,
 157,
 186,
 363,
 434,
 510,
 650,
 798,
 900,
 14,
 30,
 44,
 46,
 48,
 75,
 89,
 149,
 153,
 200,
 346,
 361,
 366,
 377,
 416,
 451,
 471,
 566,
 628,
 708,
 794,
 864,
 909,
 954,
 963,
 1023,
 1112,
 1115,
 1134,
 1136,
 1141,
 1151,
 62,
 315,
 618,
 683,
 20,
 36,
 201,
 398,
 709,
 99,
 108,
 118,
 302,
 387,
 403,
 468,
 477,
 479,
 538,
 583,
 648,
 652,
 745,
 777,
 823,
 833,
 844,
 863,
 883,
 948,
 962,
 1005,
 1089,
 1171,
 256,
 67,
 77,
 78,
 84,
 88,
 135,
 144,
 164,
 208,
 284,
 299,
 320,
 350,
 356,
 394,
 408,
 429,
 448,
 493,
 500,
 533,
 559,
 570,
 598,
 694,
 696,
 764,
 769,
 815,
 921,
 1012,
 1021,
 1135,
 18,
 50,
 79,
 90,
 141,
 187,
 188,
 196,
 221,
 233,
 248,
 278,
 322,
 329,
 401,
 456,
 501,
 551,
 604,
 626,
 632,
 637,
 641,
 658,
 666,
 691,
 697,
 704,
 706,
 715,
 756,
 760,
 774,
 790,
 834,
 857,
 867,
 940,
 965,
 1043,
 1054,
 1091,
 1100,
 1122,
 1124,
 1166,
 1181,
 5,
 6,
 10,
 21,
 57,
 61,
 147,
 154,
 198,
 207,
 212,
 217,
 220,
 240,
 246,
 296,
 300,
 306,
 331,
 379,
 490,
 495,
 498,
 504,
 509,
 534,
 542,
 555,
 562,
 580,
 585,
 607,
 654,
 655,
 699,
 702,
 734,
 776,
 797,
 809,
 880,
 958,
 972,
 1093,
 1123,
 1127,
 1140,
 1161,
 7,
 17,
 22,
 29,
 52,
 117,
 125,
 225,
 232,
 268,
 308,
 347,
 367,
 450,
 457,
 482,
 513,
 529,
 541,
 558,
 564,
 588,
 677,
 758,
 793,
 856,
 874,
 899,
 904,
 957,
 960,
 964,
 1008,
 1032,
 1132,
 1133,
 1165,
 1177,
 3162,
 13,
 64,
 70,
 81,
 112,
 119,
 137,
 152,
 184,
 266,
 283,
 349,
 362,
 372,
 600,
 735,
 742,
 845,
 1051,
 1065,
 73,
 176,
 405,
 601,
 997,
 1131,
 120,
 171,
 250,
 1074,
 129,
 1031,
 1156,
 0,
 1,
 2,
 3,
 9,
 12,
 15,
 16,
 19,
 23,
 24,
 25,
 26,
 27,
 28,
 31,
 32,
 34,
 37,
 38,
 39,
 40,
 41,
 42,
 45,
 47,
 51,
 53,
 55,
 56,
 58,
 60,
 63,
 65,
 69,
 74,
 76,
 80,
 82,
 83,
 86,
 87,
 91,
 92,
 93,
 94,
 95,
 98,
 100,
 101,
 103,
 104,
 105,
 106,
 110,
 111,
 114,
 115,
 116,
 121,
 122,
 123,
 124,
 126,
 127,
 128,
 130,
 131,
 132,
 133,
 134,
 136,
 139,
 140,
 142,
 143,
 145,
 146,
 148,
 150,
 151,
 155,
 156,
 158,
 159,
 161,
 162,
 163,
 165,
 166,
 168,
 169,
 170,
 172,
 173,
 174,
 175,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 189,
 190,
 191,
 192,
 193,
 194,
 197,
 199,
 202,
 203,
 204,
 206,
 209,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 219,
 223,
 224,
 226,
 227,
 228,
 229,
 230,
 231,
 235,
 236,
 237,
 238,
 239,
 241,
 242,
 243,
 244,
 245,
 247,
 249,
 251,
 252,
 253,
 254,
 255,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 267,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 279,
 280,
 281,
 282,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 297,
 298,
 301,
 303,
 304,
 305,
 307,
 309,
 310,
 311,
 312,
 313,
 314,
 316,
 317,
 318,
 319,
 321,
 323,
 324,
 325,
 326,
 327,
 328,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 348,
 351,
 352,
 354,
 355,
 357,
 358,
 359,
 360,
 364,
 365,
 368,
 370,
 371,
 373,
 374,
 375,
 376,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 388,
 389,
 390,
 391,
 392,
 393,
 395,
 396,
 397,
 400,
 404,
 406,
 407,
 409,
 412,
 413,
 414,
 415,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 430,
 431,
 432,
 433,
 435,
 436,
 437,
 438,
 440,
 441,
 442,
 443,
 445,
 446,
 447,
 449,
 452,
 453,
 454,
 455,
 458,
 459,
 460,
 461,
 462,
 464,
 465,
 466,
 467,
 469,
 470,
 472,
 473,
 474,
 475,
 476,
 478,
 480,
 481,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 491,
 492,
 494,
 496,
 497,
 499,
 502,
 503,
 505,
 506,
 507,
 508,
 511,
 512,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 530,
 531,
 532,
 535,
 536,
 537,
 539,
 540,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 552,
 553,
 554,
 556,
 557,
 560,
 561,
 563,
 565,
 567,
 568,
 569,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 581,
 582,
 584,
 586,
 587,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 599,
 602,
 603,
 605,
 606,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 627,
 629,
 630,
 631,
 633,
 634,
 635,
 636,
 638,
 639,
 640,
 642,
 643,
 644,
 645,
 646,
 649,
 651,
 653,
 656,
 657,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 678,
 679,
 680,
 681,
 682,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 692,
 693,
 695,
 698,
 700,
 701,
 703,
 705,
 707,
 710,
 711,
 712,
 713,
 714,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 736,
 737,
 739,
 740,
 741,
 743,
 744,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 757,
 759,
 761,
 762,
 763,
 765,
 767,
 768,
 770,
 771,
 772,
 773,
 775,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 791,
 792,
 795,
 796,
 799,
 800,
 801,
 804,
 805,
 806,
 807,
 808,
 810,
 812,
 813,
 814,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 824,
 825,
 826,
 827,
 828,
 830,
 831,
 832,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 858,
 859,
 860,
 861,
 862,
 865,
 866,
 868,
 869,
 870,
 871,
 872,
 873,
 875,
 876,
 877,
 878,
 879,
 881,
 882,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 901,
 902,
 903,
 905,
 906,
 907,
 908,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 941,
 942,
 943,
 944,
 945,
 ...]

In [19]:
selected_course_score = [i[1] for i in sorted_scores[1:]]
selected_course_score

[np.float64(0.5773502691896258),
 np.float64(0.5669467095138407),
 np.float64(0.5303300858899106),
 np.float64(0.5303300858899106),
 np.float64(0.5303300858899106),
 np.float64(0.5303300858899106),
 np.float64(0.5303300858899106),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.5),
 np.float64(0.45226701686664544),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4472135954999579),
 np.float64(0.4330127018922194),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.4082482904638631),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.3779644730092272),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.35355339059327373),
 np.float64(0.3333333333333333),
 np.float64(0.3333333333333333),
 np.float64(0.3333333333333333),
 np.float64(0.31622776601683794),
 np.float64(0.30151134457776363),
 np.float64(0.30151134457776363),
 np.float64(0.30151134457776363),
 np.float64(0.30151134457776363),
 np.float64(0.30151134457776363),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2886751345948129),
 np.float64(0.2773500981126146),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.25),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.22360679774997896),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.20412414523193154),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.1889822365046136),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.17677669529663687),
 np.float64(0.16666666666666666),
 np.float64(0.16666666666666666),
 np.float64(0.16666666666666666),
 np.float64(0.16666666666666666),
 np.float64(0.16666666666666666),
 np.float64(0.16666666666666666),
 np.float64(0.15811388300841897),
 np.float64(0.15811388300841897),
 np.float64(0.15811388300841897),
 np.float64(0.15811388300841897),
 np.float64(0.15075567228888181),
 np.float64(0.14433756729740646),
 np.float64(0.14433756729740646),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),

now, with the help of iloc functions, we will recommend similiar courses

rec_df is new df

In [20]:
rec_df = df.iloc[selected_course_index]
rec_df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,Clean_title
410,889066,Trading Options Basics,https://www.udemy.com/trading-options-basics/,True,200,8,0,8,Beginner Level,1.5 hours,2016-07-01T03:13:22Z,Business Finance,1600,2016-07-01,03:13:22Z,2016,7,1,Trading Options Basics
43,627540,Options Trading - How to Win with Weekly Options,https://www.udemy.com/work-from-home-setup-you...,True,115,7489,1190,25,Intermediate Level,1 hour,2015-10-22T21:54:28Z,Business Finance,861235,2015-10-22,21:54:28Z,2015,10,22,Options Trading Win Weekly Options
96,474928,Intermediate Options trading concepts for Stoc...,https://www.udemy.com/intermediate-options-tra...,True,40,2000,30,9,All Levels,1 hour,2015-04-13T20:28:04Z,Business Finance,80000,2015-04-13,20:28:04Z,2015,4,13,Intermediate Options trading concepts Stocks O...
138,1243448,Forex Trading with Fixed 'Risk through Options...,https://www.udemy.com/forexoptions/,True,200,611,4,26,Beginner Level,1 hour,2017-06-07T17:15:07Z,Business Finance,122200,2017-06-07,17:15:07Z,2017,6,7,Forex Trading Fixed Risk Options Trading
195,919906,Trading Options For Consistent Returns: Option...,https://www.udemy.com/trading-options-for-income/,False,0,4077,281,20,Beginner Level,1.5 hours,2016-08-18T21:57:04Z,Business Finance,0,2016-08-18,21:57:04Z,2016,8,18,Trading Options Consistent Returns Options Basics

now, we will create another column Similarity score(that will contain selected course score

In [21]:
rec_df['Similarity_score'] = selected_course_score

In [22]:
final_recommended_courses = rec_df[['course_title',\
                        'Similarity_score', 'url', 'price',\
                        'num_subscribers']]
final_recommended_courses

,course_title,Similarity_score,url,price,num_subscribers
410,Trading Options Basics,0.577350,https://www.udemy.com/trading-options-basics/,200,8
43,Options Trading - How to Win with Weekly Options,0.566947,https://www.udemy.com/work-from-home-setup-you...,115,7489
96,Intermediate Options trading concepts for Stoc...,0.530330,https://www.udemy.com/intermediate-options-tra...,40,2000
138,Forex Trading with Fixed 'Risk through Options...,0.530330,https://www.udemy.com/forexoptions/,200,611
195,Trading Options For Consistent Returns: Option...,0.530330,https://www.udemy.com/trading-options-for-income/,0,4077
...,...,...,...,...,...
3678,Learn jQuery from Scratch - Master of JavaScri...,0.000000,https://www.udemy.com/easy-jquery-for-beginner...,100,1040
3679,How To Design A WordPress Website With No Codi...,0.000000,https://www.udemy.com/how-to-make-a-wordpress-...,25,306
3680,Learn and Build using Polymer,0.000000,https://www.udemy.com/learn-and-build-using-po...,40,513
3681,CSS Animations: Create Amazing Effects on Your...,0.000000,https://www.udemy.com/css-animations-create-am...,50,300
3682,Using MODX CMS to Build Websites: A Beginner's...,0.000000,https://www.udemy.com/using-modx-cms-to-build-...,45,901

In [23]:
final_recommended_courses = final_recommended_courses[final_recommended_courses['Similarity_score']>0.5]
final_recommended_courses

,course_title,Similarity_score,url,price,num_subscribers
410,Trading Options Basics,0.577350,https://www.udemy.com/trading-options-basics/,200,8
43,Options Trading - How to Win with Weekly Options,0.566947,https://www.udemy.com/work-from-home-setup-you...,115,7489
96,Intermediate Options trading concepts for Stoc...,0.530330,https://www.udemy.com/intermediate-options-tra...,40,2000
138,Forex Trading with Fixed 'Risk through Options...,0.530330,https://www.udemy.com/forexoptions/,200,611
195,Trading Options For Consistent Returns: Option...,0.530330,https://www.udemy.com/trading-options-for-income/,0,4077
444,The Advantages of ETF Options and Index Option...,0.530330,https://www.udemy.com/learn-etf-options-and-in...,60,52
803,Options Spreads Bundle- the heart of Options ...,0.530330,https://www.udemy.com/options-spreads-explained/,120,623